version: '3'

networks:
  dashboard-net:
    name: dashboard-net

services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: dashboard-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/certs
      - ./nginxpwd:/nginxpwd
    ports:
      - "80:80"
      - "443:443"
    networks:
      - dashboard-net